#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /opt/bin/lomod --mount-dir /mnt -b /opt/lomorage --use-jpg --with-mount-mon
        procd_set_param env GOGC=50
        procd_set_param respawn
        procd_close_instance
}
